### ISSUE TITLE
tmux-open can't "work" if the current terminal is "busy"

### ISSUE THREAD

**Issue by bruno-** [tmux-plugins/tmux-open#1]
Here's the scenario where the plugin isn't working.
- start a rails server
- highlight a url in that pane (doesn't matter which url)
- press `o` to open the url in the browser

Url won't be opened because the rails server "took" the terminal.

**Comment by mgraham** [comment]
Is it possible for this to work for editing files (Ctrl-o) as well?

**Comment by bruno-** [comment]
Hey,
I'm not sure how can we make this work?
If the current terminal is "busy" (if that is the right word) with other process sending output to it, how can we run editor in it?

I guess we could make it work so that editor is opened in a new pane.. Maybe try playing with this and see what comes up? If you can make it work and it's not too complex, consider opening a pull request.
