### ISSUE TITLE
Not working after tmux 2.4

### ISSUE THREAD

**Issue by oblitum** [tmux-plugins/tmux-open#25]
See:

- https://github.com/tmux-plugins/tmux-yank/issues/76
- https://github.com/tmux-plugins/tmux-copycat/issues/109

ArchLinux has update tmux to 2.4, after this update tmux-open stopped working (given above patches applied).

**Comment by wikimatze** [comment]
Can confirm this issue. When pressing `o` it toggles jumping between the start and the end of the selection,

**Comment by docwhat** [comment]
Should be fixed by PR #24.  Reopen if it isn't.
