### ISSUE TITLE
New release, please?

### ISSUE THREAD

**Issue by weierophinney** [tmux-plugins/tmux-open#30]
#21, #24, and #28 provide support for Tmux 2.4. However, these are not yet in a new release. This is problematic when it comes to [TMUX Plugin Manager](https://github.com/tmux-plugins/tpm), as it uses the latest release when determining what to install or upgrade to; since the latest release is 2.0.0, cut 3 years ago, the way keys are bound to copy-mode is incorrect, making tmux-open unusable.

You _can_ get around it by manually doing the following:

```console
$ cd .tmux/plugins/tmux-open
$ git checkout master
```

and re-loading your tmux configuration. However, a better solution long term would be a new release of tmux-open.

**Comment by bruno-** [comment]
Done, `v3.0.0` is pushed. Thank you for reminding me.
