### ISSUE TITLE
New feature open the selected text with google

### ISSUE THREAD

**Issue by vasconcelloslf** [tmux-plugins/tmux-open#4]
Hey, this plugin is almost exactly what I wanted to de a few months ago. Back than I was eager to build a plugin that would allow me to highlight some text in copy mode and then google it. This would be especially useful to debug error messages. 

I was thinking that maybe tmux-open could have a  ```O``` binding in order to do exactly that. What do you think? If you like the idea, maybe you could give me some directions to help me build this feature? Tks.

**Comment by bruno-** [comment]
Closing since this is implemented via #8
